[package]
name = "rust-astro"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.3"
rinja_axum = "0.3.5"
tokio = { version = "1.44.2", features = ["rt-multi-thread"] }
tower-http = { version = "0.6.2", features = ["fs"] }
